title: Head Skinification Lab
description: "두피를 피부로 대하는 바이오해커의 조용한 기록"
url: "https://dailybreadeth-sketch.github.io"
baseurl: "/rlrl-blog"

permalink: /:title/
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
