title: Head Skinification Lab
description: "두피를 피부로 대하는 바이오해커의 조용한 기록"
url: "https://dailybreadeth-sketch.github.io"
baseurl: "/rlrl-blog"
timezone: Asia/Seoul
future: true



permalink: /:title/
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

plugins:
  - jekyll-sitemap
  - jekyll-relative-links

# Google Analytics 4
# GA4 측정 ID가 있다면 아래에 입력해주세요 (예: G-1234567890)
google_analytics: "G-HZP4FT8TRL"

defaults:
  - scope:
      path: "en/_posts"
      type: "posts"
    values:
      permalink: /en/:title/

